Repository MonoGame-Extended/Monogame-Extended, pull requests merged in 2024-05, with the labels that each got.

#854 Update Newtonsoft.Json.dll Dependency
  src/cs/MonoGame.Extended.Content.Pipeline/Newtonsoft.Json.dll
Labels: dependencies

#852 Resolves Infinite Recursion with Shape.Intersects(this IShapeF, IShapeF)
  src/cs/MonoGame.Extended/Math/ShapeF.cs
Labels: bug

#846 Fixes incorrect rendering of flipped animation tiles
  src/cs/MonoGame.Extended.Tiled/Renderers/TiledMapAnimatedLayerModel.cs
  src/cs/MonoGame.Extended.Tiled/Renderers/TiledMapAnimatedLayerModelBuilder.cs
  src/cs/MonoGame.Extended.Tiled/Renderers/TiledMapModelBuilder.cs
  src/cs/MonoGame.Extended.Tiled/Renderers/TiledMapRenderer.cs
  src/cs/MonoGame.Extended.Tiled/TiledMapTilesetAnimatedTile.cs
  src/cs/MonoGame.Extended.Tiled/TiledMapTilesetTileAnimationFrame.cs
Labels: bug

#869 Replace Newtonsoft.Json with System.Text.Json
  .gitattributes
  source/MonoGame.Extended.Content.Pipeline/Animations/AstridAnimatorImporter.cs
  source/MonoGame.Extended.Content.Pipeline/MonoGame.Extended.Content.Pipeline.csproj
  source/MonoGame.Extended.Content.Pipeline/Newtonsoft.Json.dll
  source/MonoGame.Extended.Content.Pipeline/TextureAtlases/TexturePackerJsonImporter.cs
  source/MonoGame.Extended.Gui/Controls/Control.cs
  source/MonoGame.Extended.Gui/Element.cs
  source/MonoGame.Extended.Gui/Screen.cs
  source/MonoGame.Extended.Gui/Serialization/AlignmentConverter.cs
  source/MonoGame.Extended.Gui/Serialization/ControlJsonConverter.cs
  source/MonoGame.Extended.Gui/Serialization/ControlStyleJsonConverter.cs
  source/MonoGame.Extended.Gui/Serialization/GuiJsonSerializer.cs
  source/MonoGame.Extended.Gui/Serialization/GuiJsonSerializerOptionsProvider.cs
  source/MonoGame.Extended.Gui/Serialization/GuiNinePatchRegion2DJsonConverter.cs
  source/MonoGame.Extended.Gui/Serialization/GuiTextureAtlasJsonConverter.cs
  source/MonoGame.Extended.Gui/Serialization/HorizontalAlignmentConverter.cs
  source/MonoGame.Extended.Gui/Serialization/SkinJsonConverter.cs
  source/MonoGame.Extended.Gui/Serialization/VerticalAlignmentConverter.cs
  source/MonoGame.Extended.Gui/Skin.cs
  source/MonoGame.Extended.Particles/ParticleEffect.cs
  source/MonoGame.Extended.Particles/ParticleEmitter.cs
  source/MonoGame.Extended.Particles/Serialization/ModifierExecutionStrategyJsonConverter.cs
  source/MonoGame.Extended.Particles/Serialization/ParticleJsonSerializer.cs
  source/MonoGame.Extended.Particles/Serialization/ParticleJsonSerializerOptionsProvider.cs
  source/MonoGame.Extended.Particles/Serialization/TimeSpanJsonConverter.cs
  source/MonoGame.Extended/MonoGame.Extended.csproj
  source/MonoGame.Extended/Serialization/BaseTypeJsonConverter.cs
  source/MonoGame.Extended/Serialization/ColorJsonConverter.cs
  source/MonoGame.Extended/Serialization/ContentManagerJsonConverter.cs
  source/MonoGame.Extended/Serialization/FloatStringConverter.cs
  source/MonoGame.Extended/Serialization/HslColorJsonConverter.cs
  source/MonoGame.Extended/Serialization/JsonContentLoader.cs
  source/MonoGame.Extended/Serialization/JsonContentTypeReader.cs
  source/MonoGame.Extended/Serialization/JsonReaderExtensions.cs
  source/MonoGame.Extended/Serialization/MonoGameJsonSerializer.cs
  source/MonoGame.Extended/Serialization/MonoGameJsonSerializerOptionsProvider.cs
  source/MonoGame.Extended/Serialization/NinePatchRegion2DJsonConverter.cs
  source/MonoGame.Extended/Serialization/RangeJsonConverter.cs
  source/MonoGame.Extended/Serialization/RectangleFJsonConverter.cs
  source/MonoGame.Extended/Serialization/ShortNameJsonContractResolver.cs
  source/MonoGame.Extended/Serialization/Size2JsonConverter.cs
  source/MonoGame.Extended/Serialization/SizeJsonConverter.cs
  source/MonoGame.Extended/Serialization/TextureRegion2DJsonConverter.cs
  source/MonoGame.Extended/Serialization/ThicknessJsonConverter.cs
  source/MonoGame.Extended/Serialization/Utf8JsonReaderExtensions.cs
  source/MonoGame.Extended/Serialization/Vector2JsonConverter.cs
  source/MonoGame.Extended/Sprites/SpriteSheetAnimationFrame.cs
  source/MonoGame.Extended/TextureAtlases/TextureAtlasJsonContentTypeReader.cs
  source/MonoGame.Extended/TextureAtlases/TextureAtlasJsonConverter.cs
  source/MonoGame.Extended/TextureAtlases/TexturePackerFile.cs
  source/MonoGame.Extended/TextureAtlases/TexturePackerMeta.cs
  source/MonoGame.Extended/TextureAtlases/TexturePackerPoint.cs
  source/MonoGame.Extended/TextureAtlases/TexturePackerRectangle.cs
  source/MonoGame.Extended/TextureAtlases/TexturePackerRegion.cs
  source/MonoGame.Extended/TextureAtlases/TexturePackerSize.cs
  tests/MonoGame.Extended.Tests/Serialization/ColorJsonConverterTests.cs
  tests/MonoGame.Extended.Tests/Serialization/RectangleFJsonConverterTest.cs
Labels: enhancement
